# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterSentiment', '0002_auto_20160321_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertext',
            name='twitter_text',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Social Updates'),
        ),
        migrations.AlterField(
            model_name='twittertext',
            name='twitter_text_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Message Id'),
        ),
        migrations.AlterField(
            model_name='twittertext',
            name='twitter_text_keyword',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='twittertext',
            name='twitter_text_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Message Timestamp'),
        ),
        migrations.AlterField(
            model_name='twittertext',
            name='twitter_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Social User ID'),
        ),
        migrations.AlterField(
            model_name='twittertext',
            name='twitter_user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Social User Name'),
        ),
    ]
