# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterSentiment', '0004_auto_20160904_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twittertext',
            old_name='twitter_text_id',
            new_name='twitter_textid',
        ),
    ]
